stages:
  - build-container

variables:
  # Define the default image name and registry (adjust these to your needs)
  DOCKER_IMAGE: gx4ki/workflow-api
  DOCKER_REGISTRY: registry.example.com

build-workflow-api:
  stage: build-container
  image: docker:20.10.21-dind
  before_script:
    - docker version
    - echo "$IMLA_CONTAINER_REGISTRY_PASS" | docker login $IMLA_CONTAINER_REGISTRY --username $IMLA_CONTAINER_REGISTRY_USER --password-stdin
  script:
    - if [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then
      TAG="${IMLA_CONTAINER_REGISTRY}/${DOCKER_IMAGE}:latest";
      elif [[ "$CI_COMMIT_REF_NAME" == "dev" ]]; then
      TAG="${IMLA_CONTAINER_REGISTRY}/${DOCKER_IMAGE}:dev";
      else
      TAG="${IMLA_CONTAINER_REGISTRY}/${DOCKER_IMAGE}:$CI_COMMIT_REF_NAME";
      fi
    - docker build --no-cache --pull -t ${TAG} .
    - docker push ${TAG}
  tags:
    - imla

  only:
    refs:
      - main
      - dev
