stages:
  - build-container

build-imla-k8s-client:
  stage: build-container
  image: docker:20.10.21-dind
  before_script:
    - docker version
    - echo "$IMLA_CONTAINER_REGISTRY_PASS" | docker login $IMLA_CONTAINER_REGESTRY --username $IMLA_CONTAINER_REGESTRY_USER --password-stdin
  script:
    - ls -al
    - docker build --no-cache --pull -t harbor.gx4ki.imla.hs-offenburg.de/gx4ki/imla-k8s-client:latest .
    - docker push harbor.gx4ki.imla.hs-offenburg.de/gx4ki/imla-k8s-client:latest
  tags:
    - imla
