version: "3"
services:

  workflow-storage:
    image: quay.io/minio/minio
    container_name: workflow-storage
    command: [
      "server",
      "/data",
      "--console-address",
      ":9090",
    ]
    volumes:
      - ./tmp/minio/:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=changeme123
      - TZ=Europe/Berlin
    networks:
      minikube:
        ipv4_address: 192.168.49.6
        aliases:
          - "workflow-storage"

  workflow-api:
    image: harbor.gx4ki.imla.hs-offenburg.de/gx4ki/workflow-api:latest
    container_name: workflow-api
    volumes:
      - ./config/workflow-api.cfg:/opt/k8s-api/config/workflow-api.cfg
      - ./config/minikube.kubeconfig:/root/.kube/config
    networks:
      minikube:
        ipv4_address: 192.168.49.5
        aliases:
          - "workflow-api"

networks:
  minikube:
    external: true
