version: '3'
services:
  entrypoint:
    image: harbor.gx4ki.imla.hs-offenburg.de/gx4ki/imla-k8s-client:latest
    container_name: entrypoint
    command: [
      "uvicorn",
      "middlelayer.entrypoint:app",
      "--workers=4",
      "--host=0.0.0.0",
      "--port=8888"
    ]
    volumes:
      - ./config/middlelayer.conf:/opt/k8s-api/config/middlelayer.conf
      # - ./middlelayer/entrypoint.py:/opt/k8s-api/middlelayer/entrypoint.py:ro
    networks:
      imla-net:
        aliases:
          - "entrypoint"
      # minikube:
      #   aliases:
      #     - "entrypoint"

networks:
  imla-net:
    external: true
  # minikube: # used for testing
  #   external: true

