version: "3"
services:

  workflow-storage:
    image: quay.io/minio/minio
    container_name: workflow-storage
    command: [
      "server",
      "/data",
      "--console-address",
      ":9001",
    ]
    volumes:
      - ./tmp/minio/:/data
    environment:
      - MINIO_ROOT_USER=rootuser
      - MINIO_ROOT_PASSWORD=rootpass123
      - TZ=Europe/Berlin
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      minikube:
        ipv4_address: 192.168.49.6
        aliases:
          - "workflow-storage"

  workflow-api:
    build: .
    image: gx4ki/workflow-api:latest
    container_name: workflow-api
    volumes:
      - ./config/workflow-api.cfg:/opt/config/workflow-api.cfg
      - ./config/kube/config:/root/.kube/config
      - ./config/assets:/opt/assets
    networks:
      minikube:
        ipv4_address: 192.168.49.5
        aliases:
          - "workflow-api"

networks:
  minikube:
    external: true
