version: "3"
services:

  # TODO service_api

  workflow-storage:
    image: quay.io/minio/minio
    container_name: workflow-storage
    command: [
      "server",
      "/data",
      "--console-address",
      ":9090",
    ]
    volumes:
      - ./tmp/minio/:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=changeme123
      - TZ=Europe/Berlin
      # - MINIO_BROWSER_REDIRECT_URL=http://localhost/uuid/storage-web
    network_mode: host

  workflow-api:
    image: harbor.gx4ki.imla.hs-offenburg.de/gx4ki/workflow-api:latest
    container_name: workflow-api
    volumes:
      - ./config/workflow-api.local.cfg:/opt/k8s-api/config/workflow-api.cfg
      - ./config/minikube.kubeconfig:/root/.kube/config
    # network_mode: host

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  data-side-car:
    image: harbor.gx4ki.imla.hs-offenburg.de/gx4ki/data-side-car:latest
    container_name: data-side-car
    ports:
      - 9999:9999
    profiles:
      - "data-side-car"
