version: "3"
services:

  # TODO service_api

  workflow-storage:
    image: quay.io/minio/minio
    container_name: workflow-storage
    command: [
      "server",
      "/data",
      "--console-address",
      ":9090",
    ]
    user:
      1000:1000
    volumes:
      - ./tmp/minio/:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=changeme123
      - TZ=Europe/Berlin
    network_mode: host
    # networks:
    #   imla-net:
    #     ipv4_address: 192.168.205.6
    #     aliases:
    #       - workflow_storage

  data-side-car:
    image: harbor.gx4ki.imla.hs-offenburg.de/gx4ki/data-side-car:latest
    container_name: data-side-car
    ports:
      - 9999:9999
    profiles:
      - "data-side-car"

networks:
  workflow-net:
    external: true