@startuml sq-overview-middlelayer

edc_provider -> gx4ki_ml_entrypoint: **post** /provision/

gx4ki_ml_entrypoint -> gx4ki_ml_entrypoint: create <thread>
activate gx4ki_ml_entrypoint #Salmon

gx4ki_ml_entrypoint -> gx4ki_ml_k8s_client: **get** /demo/

activate gx4ki_ml_k8s_client #DarkSalmon

gx4ki_ml_k8s_client -> k8s_api: apply gx4ki_job

gx4ki_ml_k8s_client -> gx4ki_ml_k8s_client: wait for result
activate gx4ki_ml_k8s_client #Salmon

k8s_api -> gx4ki_job: <<schedule job>>
activate gx4ki_job #LightGreen

gx4ki_ml_k8s_client --> gx4ki_job: watch job status

gx4ki_job -> gx4ki_job: get input data
gx4ki_job -> gx4ki_job: do entrypoint


gx4ki_ml_k8s_client <-> gx4ki_job : exec into data-side-car\nand store data
deactivate gx4ki_job
deactivate gx4ki_ml_k8s_client

gx4ki_ml_k8s_client -> gx4ki_ml_entrypoint: **return** job_data
deactivate gx4ki_ml_k8s_client


gx4ki_ml_entrypoint -> edc_provider: **post** /callback/<transferid>
deactivate gx4ki_ml_entrypoint
@enduml
