apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gx4ki-cr
rules:
  - nonResourceURLs: ["/healthz", "/readyz", "/livez"]
    verbs: ["get"]
  - apiGroups:
      - ""
    resources: ["pods", "pods/exec"]
    verbs: ["get", "delete", "create", "exec", "list"]
  - apiGroups:
      - ""
    resources: ["configmaps"]
    verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gx4ki-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gx4ki-cr
subjects:
  - kind: ServiceAccount
    name: gx4ki-sa
    namespace: gx4ki-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gx4ki-sa
  namespace: gx4ki-demo
