apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gx4ki-cr
rules:
- apiGroups:
  - ""
  resources: ["pods", "pods/exec"]
  verbs: ["get", "exec", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "create", "delete"]